### ISSUE TITLE
Implementar novo formato alfanumérico para CNPJ 

### ISSUE THREAD

**Issue by klawdyo** [klawdyo/validation-br#11]
Fonte: https://www.contabeis.com.br/noticias/65594/novo-cnpj-receita-federal-anuncia-mudancas-no-cadastro-de-empresas/
Nota técnica: [Nota COCAD SUARA 2024 05 49 CNPJ Alfanumerico-1.pdf](https://github.com/user-attachments/files/15851229/Nota.COCAD.SUARA.2024.05.49.CNPJ.Alfanumerico-1.pdf)

**Comment by NedcloarBR** [comment]
Sugestão para este futuro update
Passar um parametro do tipo `boolean` para a função que gera o CNPJ com o intuito de gerar o CNPJ no padrão novo ou no antigo.
