### ISSUE TITLE
Validação permitindo documentos com mais caracteres que o padrão

### ISSUE THREAD

**Issue by igor-sillva** [klawdyo/validation-br#7]
A biblioteca está validando qualquer entrada onde seja os caracteres iniciais um cpf valido e o restante qualquer valor.
Por exemplo:

```js
import { isCPF } from 'validation-br';

isCPF('123456789099999999999999999999999999999999999999999999999999999999');
// return true
```

**Comment by klawdyo** [comment]
Boa tarde. 
Vou fazer meus testes e te dou o retorno esta semana.

**Comment by klawdyo** [comment]
De fato. 

Por design eu considerei que um número do tipo 1234567890 é igual a 01234567890. Ou seja: eu sempre adiciono zeros à esquerda antes de validar. A função que faz esse tratamento também corta o número passado como parâmetro, por isso que o seu exemplo é validado: A função remove os caracteres extras à direita e isso realmente não deveria acontecer em uma validação. Talvez em uma sanitização. Mas não é o caso.

Creio que devo subir uma correção amanhã.

Valeu pelo aviso.

**Comment by klawdyo** [comment]
Atualização com possível break changes nas validações.

- [ ]  [release] Atualizar para versão 2.0.0 (possível break change devido à mudança no tratamento dos dados a serem validados).
- [ ]  [feat] Adicionar um `sanitize()` às classes de documentos para concentrar a sanitização dos valores.
- [ ] [fix] O número validado não deve mais cortar os números à direita. Ele deve respeitar o tamanho máximo.
- [ ] [fix] O clearNumber() deve receber um parâmetro de configuração que permitirá cortar os números à direita ou não cortar. Esta configuração só será true nas chamadas feitas pelo `sanitize()`.
- [ ]  [bug] A validação está permitindo o número com mais caracteres que o máximo.
- [ ] [test] Atualizar os testes com o `sanitize()`e os números com mais caracteres que o máximo.
- [ ]  [docs] Atualizar o readme com as informações da função `sanitize()`.

**Comment by klawdyo** [comment]
Atualizações publicadas.
